services:
  app-prod:
    container_name: mu-digital-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always

    ports:
      - "192.168.1.26:80:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=4000
      - HOSTNAME=0.0.0.0
      - ENABLE_IP_GUARD=${ENABLE_IP_GUARD}